# Generated by Django 4.0 on 2021-12-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_historicalboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%Y/%m'),
        ),
    ]
