# Generated by Django 4.0 on 2021-12-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_topic_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='file',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.topic'),
        ),
    ]
