# Generated by Django 4.0 on 2021-12-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_remove_photo_photo_remove_photo_topic_photo_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.topic'),
        ),
    ]
