# Generated by Django 3.2.10 on 2022-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_board_is_active_historicalboard_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
