version: '3.7'
services:
  web: 
    container_name: simple-django-api
    build: ./
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  celery:
    build: ./
    command: celery -A core worker -l info
    volumes:
      - ./:/urs/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis 
      - web
    
  celery-beat:
    build: ./
    command: celery -A core worker -l info
    volumes:
      - ./:/urs/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis 
      - web

volumes:
  postgres_data: