# Generated by Django 4.0 on 2021-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.AddField(
            model_name='blogger',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='reader',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar/'),
        ),
    ]
