# Generated by Django 3.2.10 on 2022-01-04 13:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_avatar_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
