# Generated by Django 4.0 on 2021-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
