# Generated by Django 4.0 on 2021-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_avatar_blogger_avatar_reader_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar/'),
        ),
    ]
