# Generated by Django 4.0 on 2021-12-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.FileField(blank=True, upload_to='image/%Y/%m'),
        ),
    ]
