# Generated by Django 4.0 on 2021-12-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.file'),
        ),
    ]
