# Generated by Django 4.0 on 2021-12-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_photo_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='topic',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
