# Generated by Django 4.0 on 2021-12-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_photo_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalboard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
